version: 2.1

jobs:
  test:
    parameters:
      php-version:
        type: string
      zipkin-php-version:
        type: string
    docker:
      - image: cimg/php:<< parameters.php-version >>-browsers
    working_directory: ~/zipkin-doctrine
    steps:
      - checkout
      - run: composer install -n
      - run: composer require openzipkin/zipkin:"^<< parameters.zipkin-php-version >>"
      - run:
          name: Run lint
          command: composer lint
      - run:
          name: Run tests
          command: composer test

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              php-version: ["5.6", "7.0", "7.1", "7.2"]
              zipkin-php-version: ["1.3.6", "2.0"]
            exclude:
              - php-version: "5.6"
                zipkin-php-version: "2.0"
              - php-version: "7.0"
                zipkin-php-version: "2.0"
